### ISSUE TITLE
`KMockitoAnnotations` is replaced by `MockAnnotations` in 0.3.0

### ISSUE THREAD

**Issue by yuanhang** [wickie73/mockito4kotlin.annotation#1]
Hi, it seems that `KMockitoAnnotations` is replaced by `MockAnnotations` in 0.3.0. So the instructions in `README.md` is no longer valid. I was intended to create a PR to fix this, however, I found that the code base in master branch still contains `KMockitoAnnotations` not `MockAnnotations` in 0.3.0. Seems the code in master branch is not sync with the 0.3.0 tag. I'm not sure if it is intended so I create this issue.

**Comment by wickie73** [comment]
Thank you for your feedback.

`MockAnnotations` in _version 0.3.0_ has been replaced by class `KMockitoAnnotations` in _master branch_. It's to express more strongly that it belongs to Kotlin-based Mockito and not the Mockito lib itself. 

I will create _version 0.4.0_ soon which will be in sync with _master branch_.

**Comment by yuanhang** [comment]
Thanks for the explanation. Then I will close this issue.

**Comment by wickie73** [comment]
Version 0.4.0 has been created.
