### ISSUE TITLE
Could not resolve org.mockito4kotlin:annotation:0.4.0

### ISSUE THREAD

**Issue by garwedgess** [wickie73/mockito4kotlin.annotation#2]
I am trying to use v0.4.0 but it cannot be found. Looking at the maven-metadata.xml the latest version is 0.3.0:

`<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.mockito4kotlin</groupId>
  <artifactId>annotation</artifactId>
  <version>0.3.0</version>
  <versioning>
    <latest>0.3.0</latest>
    <release>0.3.0</release>
    <versions>
      <version>0.2.5</version>
      <version>0.2.7</version>
      <version>0.3.0</version>
    </versions>
    <lastUpdated>20180603192851</lastUpdated>
  </versioning>
</metadata>`

Thanks

**Comment by wickie73** [comment]
I could not fix it quickly, so it will take a bit longer. 

In the meantime you can download the artifacts from here: https://dl.bintray.com/wickie73/wickieMaven/

**Comment by garwedgess** [comment]
This is what I have done in the meantime. There's no rush, just making you aware of it.

Thanks
